replicaCount: 3

image:
  repository: us-east1-docker.pkg.dev/helm-tut/quickstart-docker-repo/helm-app
  tag: latest
  pullPolicy: Always

  service:
    type: NodePort
    port: 80

app_port: 3000
environment: production