apiVersion: v1
kind: Service
metadata:
    name: {{ include "my-app.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "my-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    selector:
        app.kubernetes.io/name: {{ include "my-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
        - protocol: TCP
            port: 80
            targetPort: 8080
    type: ClusterIP